spring:
  profiles:
    active: local

---


spring:
  profiles: default
  application:
    name: gia
  http:
    encoding:
      force: true
      force-request: true
      force-response: true
  mvc:
    servlet:
      load-on-startup: 1
      multipart:
        enabled: true
        file-size-threshold: 0
        max-file-size: 3MB
        location: ./uploads
        max-request-size: 10MB
        resolve-lazily: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    #    mapping-resources:
    #    properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
      ddl-auto: validate
      use-new-id-generator-mappings: false
      jdbc:
        time_zone: UTC
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  data:
    jpa:
      repositories:
        #        bootstrap-mode:
        enabled: true

---

spring:
  profiles: db
  datasource:
#    url: "jdbc:mysql://localhost:3306/korbit?autoReconnection-true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    username: kepha
#    password: kepha
    korbit:
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbc-url: "jdbc:mysql://localhost:3306/korbit?autoReconnection-true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: kepha
      password: kepha
      connection-init-sql: "select 1 from dual"
      connection-test-query: "select 1 from dual"
      #      schema:
      minimum-idle: 10
      idle-timeout: 600000
      auto-commit: true
      allow-pool-suspension: false
      #      catalog:
      #      data-source-j-n-d-i:
      #      data-source-class-name:
      connection-timeout: 70000
      data-source-properties: "{password=<kepha>}"
      health-check-properties: "{}"
      #      health-check-registry:
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      leak-detection-threshold: 0
      max-lifetime: 1800000
      maximum-pool-size: 10
      #      metric-registry: com.codahale.metrics.MetricRegistry
      #      metrics-tracker-factory: com.zaxxer.hikari.metrics.MetricsTracker
      read-only: false
      register-mbeans: false
      #      scheduled-executor:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      login-timeout: 70000
      pool-name: HikariPool1
      validation-timeout: 5000
      hikari:
        idle-timeout: 10000
    korbitapi:
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbc-url: "jdbc:mysql://localhost:3306/korbit_api?autoReconnection-true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: kepha
      password: kepha
      connection-init-sql: "select 1 from dual"
      connection-test-query: "select 1 from dual"
      #      schema:
      minimum-idle: 10
      idle-timeout: 600000
      auto-commit: true
      allow-pool-suspension: false
      #      catalog:
      #      data-source-j-n-d-i:
      #      data-source-class-name:
      connection-timeout: 70000
      data-source-properties: "{password=<kepha>}"
      health-check-properties: "{}"
      #      health-check-registry:
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      leak-detection-threshold: 0
      max-lifetime: 1800000
      maximum-pool-size: 10
      #      metric-registry: com.codahale.metrics.MetricRegistry
      #      metrics-tracker-factory: com.zaxxer.hikari.metrics.MetricsTracker
      read-only: false
      register-mbeans: false
      #      scheduled-executor:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      login-timeout: 70000
      pool-name: HikariPool1
      validation-timeout: 5000
    terra:
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbc-url: "jdbc:mysql://localhost:3306/terra?autoReconnection-true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      username: kepha
      password: kepha
      connection-init-sql: "select 1 from dual"
      connection-test-query: "select 1 from dual"
      #      schema:
      minimum-idle: 10
      idle-timeout: 600000
      auto-commit: true
      allow-pool-suspension: false
      #      catalog:
      #      data-source-j-n-d-i:
      #      data-source-class-name:
      connection-timeout: 70000
      data-source-properties: "{password=<kepha>}"
      health-check-properties: "{}"
      #      health-check-registry:
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      leak-detection-threshold: 0
      max-lifetime: 1800000
      maximum-pool-size: 10
      #      metric-registry: com.codahale.metrics.MetricRegistry
      #      metrics-tracker-factory: com.zaxxer.hikari.metrics.MetricsTracker
      read-only: false
      register-mbeans: false
      #      scheduled-executor:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
      login-timeout: 70000
      pool-name: HikariPool1
      validation-timeout: 5000
      hikari:
        idle-timeout: 10000

---

spring:
  priofiles: logging
logging:
  config: classpath:logback.xml
  level:
    root: info
    java:
      sql: debug
      sqlonly: debug
      sqltiming: debug
      audit: debug
      resultset: debug
    org.hibernate: warn
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    kr.co.korbit: debug
    java.sql: debug
    java.sql.Connection: info
    java.sql.Statement: info
    java.sql.PreparedStatement: debug
    java.sql.ResultSet: debug
    com.google.android.gcm.server: debug
    org.springframework.orm: warn
    org.springframework.core: warn
    org.springframework.beans: warn
    org.springframework.context: warn
    org.springframework.aop: warn
    org.springframework.web: info
    org.springframework.transaction: warn
    org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor: error
    org.springframework.data.redis.core.RedisConnectionUtils: warn
    org.springframework.web.servlet.mvc.method.annotation: trace
    org.springframework.web.servlet: info
    org.springframework.jdbc.core: warn
    org.apache.commons: info
    org.springframework.jdbc.datasource.DataSourceTransactionManager: error
    org.mybatis.spring.SqlSessionUtils: error
    com.zaxxer.hikari: debug
    com.fasterxml.jackson.core: debug
    com.spring.ibatis: debug
    org.mybatis.spring.boot: error


---

spring:
  profiles: local
    - default
    - jpa
    - db
    - logging
